apiVersion: apps/v1
kind: Deployment
metadata:
  name: meridian-kafka-poc-producer
  labels:
    meridian-app: kafka-poc
    appid: some-app-id 
spec:
  replicas: 1
  selector:
    matchLabels:
      meridian-app: kafka-poc
  template:
    metadata:
      labels:
        meridian-app: kafka-poc
    spec:
      containers:
      - name: kafka-producer-container
        image: kafka-poc-producer-0.0.1:latest
        imagePullPolicy: Never
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: meridian-kafka-poc-config
