apiVersion: apps/v1
kind: Deployment
metadata:
  name: meridian-kafka-poc-consumer
  labels:
    meridian-app: kafka-poc
    appid: some-app-id 
spec:
  replicas: 1
  selector:
    matchLabels:
      meridian-app: kafka-poc
  template:
    metadata:
      labels:
        meridian-app: kafka-poc
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: config
        secret:
            secretName: meridian-kafka-poc-config
      containers:
      - name: nginx-container
        image: nginx
        volumeMounts:
          - name: shared-data
            mountPath: /usr/share/nginx/html
        ports:
          - containerPort: 8080
      - name: kafka-consumer-container
        image: kafka-poc-consumer-0.0.1:latest
        imagePullPolicy: Never
        volumeMounts:
          - name: shared-data
            mountPath: /pod-data
          - name: config
            mountPath: /etc/config
            readOnly: true
