FROM quay.io/arubadevops/ubuntu:golang114-dev-latest as builder

RUN apt-get update && apt-get install -y git-core

# set the working directory
WORKDIR $GOPATH/src/stash.arubanetworks.com/ac/meridian-positioning-service/services

# copy context
COPY kafka_poc ./kafka_poc
COPY go.mod .

# build executable to /app
RUN CGO_ENABLED=0 go build \
    -installsuffix 'static' \
    -o /app \
    kafka_poc/cmd/consumer/main.go

WORKDIR /

ENTRYPOINT ["/app"]
